
name: training_project

profile: fishtown-redshift

version: '1.0'

require-dbt-version: ">=0.15.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

seeds:
  quote_columns: false
  
models:
  bind: false
  training_project:
    staging:
      materialize: view
    marts:
      materialize: table